### ISSUE TITLE
serialize anonymous object broken

### ISSUE THREAD

**Issue by rjanicek** [cloudshift/hx-node#10]
node.js 0.8.4 x64 / Haxe 2.10 / Windows

-include hx-node in class path

test.hx: 

``` haxe
package ;
import haxe.Serializer;
class Main {
    static function main() {
        Serializer.run( { } );
    }
}
```

output in node and browser ->

TypeError: Object function () { } has no method 'getClass'

Suspect problem is with changes to js.Boot.hx from Haxe 2.10 release

Possible similar issue: https://groups.google.com/forum/?fromgroups#!msg/haxelang/z0Qymrm3smQ/Xak-uMR41OMJ

**Comment by rjanicek** [comment]
Deleting js\Boot.hx seems to fix the problem. Is this file necessary for hx-node ?

**Comment by cloudshift** [comment]
I'm removing it now, it's not necessary with 2.1o

**Comment by rjanicek** [comment]
Did you remove it? Looks like it's still there.
https://github.com/cloudshift/hx-node/blob/master/js/Boot.hx

Thanks,
§ Richard Janicek
www.Clock2D.com

On Mon, Jul 30, 2012 at 8:27 AM, Ritchie Turner <
reply@reply.github.com
