### ISSUE TITLE
writeHead is broken

### ISSUE THREAD

**Issue by janekp** [cloudshift/hx-node#11]
The current writeHead function is defined as:

```
function writeHead(statusCode:Int,?reasonPhrase:String,?headers:Dynamic):Void;
```

Unfortunately this is problematic, because the way optional parameters are handled in NodeJS/Javascript. If i type:

```
res.writeHead(200, { "Header": "Value" });
```

then it will be compiled to:

```
res.writeHead(200, null, { "Header": "Value" });
```

But that won't work as expected and custom headers will be omitted. The function needs an overload to solve this problem:

```
@:overload(function(statusCode:Int,?reasonPhrase:String,?headers:Dynamic):Void {})
function writeHead(statusCode:Int,headers:Dynamic):Void;
```

**Comment by cloudshift** [comment]
thanks adding now.
