### ISSUE TITLE
js.Boot.getClass() not found under Haxe 2.10

### ISSUE THREAD

**Issue by mikestead** [cloudshift/hx-node#12]
When I compile and run my node js server file using Haxe 2.10 I soon get the following runtime error:

```
return js.Boot.getClass(o);
        ^
TypeError: Object function () { } has no method 'getClass'
```

Which I believe is down to how hx-node overrides the Boot class.

This was also reported on the Haxe mailing list a while back but don't think was logged here.

https://groups.google.com/d/msg/haxelang/z0Qymrm3smQ/Xak-uMR41OMJ

**Comment by cloudshift** [comment]
On 08/08/2012 03:08 AM, Mike Stead wrote:

> When I compile and run my node js server file using Haxe 2.10 I soon 
> get the following runtime error:
> 
> |return js.Boot.getClass(o);
>          ^
> TypeError: Object function () { } has no method 'getClass'
> |
> 
> Which I believe is down to how hx-node overrides the Boot class.
> 
> This was also reported on the Haxe mailing list a while back but don't 
> think was logged here.
> 
> https://groups.google.com/d/msg/haxelang/z0Qymrm3smQ/Xak-uMR41OMJ
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/cloudshift/hx-node/issues/12.
> 
> Hi Mike,

I've removed Boot.hx from github, it's not necessary anymore. I'd 
forgotten to git rm it.

Thanks

R

**Comment by mikestead** [comment]
Great, that seemed to fix the problem. Will you be pushing out this update to the haxelib?

**Comment by cloudshift** [comment]
On 08/10/2012 12:23 AM, Mike Stead wrote:

> Great, that seemed to fix the problem. Will you be pushing out this 
> update to the haxelib?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/cloudshift/hx-node/issues/12#issuecomment-7633923.
> 
> yes, I'll do this morning

R

**Comment by mikestead** [comment]
Thanks for resolving this
